//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAssist.UI.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicalAssist.UI.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is already verified..
        /// </summary>
        internal static string AccountIsVerified {
            get {
                return ResourceManager.GetString("AccountIsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified..
        /// </summary>
        internal static string AccountVerifiedSuccess {
            get {
                return ResourceManager.GetString("AccountVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmedPassword {
            get {
                return ResourceManager.GetString("ConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is already taken. .
        /// </summary>
        internal static string CreateAccountEmailInUsePrompt {
            get {
                return ResourceManager.GetString("CreateAccountEmailInUsePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currents.
        /// </summary>
        internal static string Currents {
            get {
                return ResourceManager.GetString("Currents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email pattern..
        /// </summary>
        internal static string EmailInvalidPattern {
            get {
                return ResourceManager.GetString("EmailInvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty!.
        /// </summary>
        internal static string Empty_Email {
            get {
                return ResourceManager.GetString("Empty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!.
        /// </summary>
        internal static string Empty_Password {
            get {
                return ResourceManager.GetString("Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name cannot be empty..
        /// </summary>
        internal static string EmptyFullname {
            get {
                return ResourceManager.GetString("EmptyFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too long..
        /// </summary>
        internal static string FullNameTooLong {
            get {
                return ResourceManager.GetString("FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too short..
        /// </summary>
        internal static string FullNameTooShort {
            get {
                return ResourceManager.GetString("FullNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to main page.
        /// </summary>
        internal static string GoToMainPage {
            get {
                return ResourceManager.GetString("GoToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account uses an external authentication system ( Google or Facebook)..
        /// </summary>
        internal static string InvalidLoginProviderError {
            get {
                return ResourceManager.GetString("InvalidLoginProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        internal static string InvalidSignInCredentialsError {
            get {
                return ResourceManager.GetString("InvalidSignInCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, loading ....
        /// </summary>
        internal static string LoadingScreen {
            get {
                return ResourceManager.GetString("LoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you not have an account ?.
        /// </summary>
        internal static string LoginPageDontHaveAccountQuestion {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string LoginPageRegisterLink {
            get {
                return ResourceManager.GetString("LoginPageRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string LogOut_Dialog {
            get {
                return ResourceManager.GetString("LogOut_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Assistant.
        /// </summary>
        internal static string MedicalAssist {
            get {
                return ResourceManager.GetString("MedicalAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must matches..
        /// </summary>
        internal static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long. Maximum length is {0}..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short. Minimal length is {0}..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email with the verification code has been sent..
        /// </summary>
        internal static string RegenerateCodeEmailSent {
            get {
                return ResourceManager.GetString("RegenerateCodeEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code Regeneration.
        /// </summary>
        internal static string RegenerateCodePageTitle {
            get {
                return ResourceManager.GetString("RegenerateCodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again verification link.
        /// </summary>
        internal static string RegenerateCodeSendAgain {
            get {
                return ResourceManager.GetString("RegenerateCodeSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was successfully set up..
        /// </summary>
        internal static string RegisterPageAccountCreated {
            get {
                return ResourceManager.GetString("RegisterPageAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation link was sent to your email address..
        /// </summary>
        internal static string RegisterPageEmailSent {
            get {
                return ResourceManager.GetString("RegisterPageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string RegisterPageLoginLink {
            get {
                return ResourceManager.GetString("RegisterPageLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account ?.
        /// </summary>
        internal static string RegisterPageQuestion {
            get {
                return ResourceManager.GetString("RegisterPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has not yet been activated..
        /// </summary>
        internal static string UnverifiedUserError {
            get {
                return ResourceManager.GetString("UnverifiedUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with given email was not found..
        /// </summary>
        internal static string UserNotFoundByGivenEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByGivenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code has expired..
        /// </summary>
        internal static string VerificationCodeExpiredLabel {
            get {
                return ResourceManager.GetString("VerificationCodeExpiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new code.
        /// </summary>
        internal static string VerificationCodeNewCode {
            get {
                return ResourceManager.GetString("VerificationCodeNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
