version: '3.4'
name: medicalassist
services:
  medicalassist.api:
    image: ${DOCKER_REGISTRY-}medicalassistapi
    container_name: medicalassist.api
    build:
      context: .
      dockerfile: MedicalAssist.API/Dockerfile
    networks:
      - medical-assist-network
    ports:
    - "5000:5000"
    - "5001:5001"
    environment:
     - RUNNING_IN_DOCKER=true
    depends_on:
      - medicalassist.database
  medicalassist.seq:
    image: datalust/seq:latest
    container_name: medicalassist.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
     - 5341:5341
     - 5100:80 
    networks:
      - medical-assist-network

  medicalassist.database:
    image: postgres:latest
    container_name: medicalassist.database
    networks:
      - medical-assist-network
    environment:
    - POSTGRES_DB=medicalassist
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./.cointainers/medicalassist-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  medicalassist.ui:
    container_name: medicalassist.ui
    build:
      context: ./MedicalAssist.UI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./MedicalAssist.UI/nginx.conf:/etc/nginx/nginx.conf
      - ./Certificates:/etc/ssl/certs
      - ./Certificates:/etc/ssl/private
    networks:
      - medical-assist-network
    depends_on:
      - medicalassist.api
  medicalassist.pgadmin:
     container_name: medicalassist.pgadmin
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: admin
     ports:
        - "5050:80"
     networks:
      - medical-assist-network

networks:
  medical-assist-network:
    driver: bridge