//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAssistant.UI.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicalAssistant.UI.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the.
        /// </summary>
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been successfully deactivated..
        /// </summary>
        internal static string AccountDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate your account ?.
        /// </summary>
        internal static string AccountDeactivationPrompt {
            get {
                return ResourceManager.GetString("AccountDeactivationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been successfully deleted..
        /// </summary>
        internal static string AccountDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account ?.
        /// </summary>
        internal static string AccountDeletePrompt {
            get {
                return ResourceManager.GetString("AccountDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active..
        /// </summary>
        internal static string AccountIsNotActive {
            get {
                return ResourceManager.GetString("AccountIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is already verified..
        /// </summary>
        internal static string AccountIsVerified {
            get {
                return ResourceManager.GetString("AccountIsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified..
        /// </summary>
        internal static string AccountVerifiedSuccess {
            get {
                return ResourceManager.GetString("AccountVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation link expired ?.
        /// </summary>
        internal static string ActivationLinkExpired {
            get {
                return ResourceManager.GetString("ActivationLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment.
        /// </summary>
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a Stage of Disease.
        /// </summary>
        internal static string AddingDiseaseStage {
            get {
                return ResourceManager.GetString("AddingDiseaseStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the medication.
        /// </summary>
        internal static string AddingMedication {
            get {
                return ResourceManager.GetString("AddingMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notification.
        /// </summary>
        internal static string AddNotification {
            get {
                return ResourceManager.GetString("AddNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        internal static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the tag and press +.
        /// </summary>
        internal static string AddTagComment {
            get {
                return ResourceManager.GetString("AddTagComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Visit.
        /// </summary>
        internal static string AddVisitBtn {
            get {
                return ResourceManager.GetString("AddVisitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Visit.
        /// </summary>
        internal static string AddVisitTitle {
            get {
                return ResourceManager.GetString("AddVisitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon recommendations.
        /// </summary>
        internal static string AfternoonRecommendations {
            get {
                return ResourceManager.GetString("AfternoonRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Visits.
        /// </summary>
        internal static string AllVisits {
            get {
                return ResourceManager.GetString("AllVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Terms of Service - Medical Assistant.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the attachment ?.
        /// </summary>
        internal static string AttachmentDeletePrompt {
            get {
                return ResourceManager.GetString("AttachmentDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string BackToLoginScreen {
            get {
                return ResourceManager.GetString("BackToLoginScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a visit.
        /// </summary>
        internal static string ChooseVisit {
            get {
                return ResourceManager.GetString("ChooseVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city name cannot be empty..
        /// </summary>
        internal static string CityCannotBeEmpty {
            get {
                return ResourceManager.GetString("CityCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1. The user uses the Application voluntarily and at their own risk..
        /// </summary>
        internal static string Condition1 {
            get {
                return ResourceManager.GetString("Condition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2. Using the Application requires consent to the processing of personal data, including medical data, in accordance with the Privacy Policy..
        /// </summary>
        internal static string Condition2 {
            get {
                return ResourceManager.GetString("Condition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3. The user is required to use the Application in accordance with the law and these terms..
        /// </summary>
        internal static string Condition3 {
            get {
                return ResourceManager.GetString("Condition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4. Users are prohibited from providing illegal content, including false medical data, infringing third-party rights, or content that is harmful or fraudulent..
        /// </summary>
        internal static string Condition4 {
            get {
                return ResourceManager.GetString("Condition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Terms of Use.
        /// </summary>
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmedPassword {
            get {
                return ResourceManager.GetString("ConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is already taken. .
        /// </summary>
        internal static string CreateAccountEmailInUsePrompt {
            get {
                return ResourceManager.GetString("CreateAccountEmailInUsePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currents.
        /// </summary>
        internal static string Currents {
            get {
                return ResourceManager.GetString("Currents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        internal static string CurrentWeek {
            get {
                return ResourceManager.GetString("CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Diagnosis.
        /// </summary>
        internal static string DateOfDiagnosis {
            get {
                return ResourceManager.GetString("DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sent.
        /// </summary>
        internal static string DateSent {
            get {
                return ResourceManager.GetString("DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Account.
        /// </summary>
        internal static string DeactivateAccount {
            get {
                return ResourceManager.GetString("DeactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1. &lt;strong&gt;Application&lt;/strong&gt; – software available online or for download, known as &apos;Medical Assistant&apos;, designed to help users manage their medical and health data..
        /// </summary>
        internal static string Definition1 {
            get {
                return ResourceManager.GetString("Definition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2. &lt;strong&gt;User&lt;/strong&gt; – any person accessing the Application, regardless of the access method (web, mobile)..
        /// </summary>
        internal static string Definition2 {
            get {
                return ResourceManager.GetString("Definition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3. &lt;strong&gt;Medical Data&lt;/strong&gt; – any information related to the user&apos;s health, including medical history, test results, recorded visits, medical recommendations, and other data entered by the user into the Application..
        /// </summary>
        internal static string Definition3 {
            get {
                return ResourceManager.GetString("Definition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4. &lt;strong&gt;Administrator&lt;/strong&gt; – the application owner responsible for its operation and development..
        /// </summary>
        internal static string Definition4 {
            get {
                return ResourceManager.GetString("Definition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachment.
        /// </summary>
        internal static string DeleteAttachment {
            get {
                return ResourceManager.GetString("DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete visit.
        /// </summary>
        internal static string DeleteSelectedVisit {
            get {
                return ResourceManager.GetString("DeleteSelectedVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this notification ?.
        /// </summary>
        internal static string DeletingNotificationQuestion {
            get {
                return ResourceManager.GetString("DeletingNotificationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entry ?.
        /// </summary>
        internal static string DialogDeleteNote {
            get {
                return ResourceManager.GetString("DialogDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting note.
        /// </summary>
        internal static string DialogDeleteNoteTitle {
            get {
                return ResourceManager.GetString("DialogDeleteNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Stage Removal.
        /// </summary>
        internal static string DialogDiseaseStageDelete {
            get {
                return ResourceManager.GetString("DialogDiseaseStageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this stage of the disease ?.
        /// </summary>
        internal static string DialogEditDiseaseStageRemove {
            get {
                return ResourceManager.GetString("DialogEditDiseaseStageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Medical History.
        /// </summary>
        internal static string DialogMedicalHistoryDeleteConfirmation {
            get {
                return ResourceManager.GetString("DialogMedicalHistoryDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting an Entry from Medical History.
        /// </summary>
        internal static string DialogMedicalHistoryRemoving {
            get {
                return ResourceManager.GetString("DialogMedicalHistoryRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to remove the entry from the medical history ?.
        /// </summary>
        internal static string DialogRemoveMedicalHistory {
            get {
                return ResourceManager.GetString("DialogRemoveMedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this recommendation ?.
        /// </summary>
        internal static string DialogRemoveMedication {
            get {
                return ResourceManager.GetString("DialogRemoveMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this entry from your medical history ?.
        /// </summary>
        internal static string DialogRemoweMedicatalHistory {
            get {
                return ResourceManager.GetString("DialogRemoweMedicatalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing a Visit.
        /// </summary>
        internal static string DialogVisitRemoving {
            get {
                return ResourceManager.GetString("DialogVisitRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this visit ?.
        /// </summary>
        internal static string DialogVisitRemovingPrompt {
            get {
                return ResourceManager.GetString("DialogVisitRemovingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease History.
        /// </summary>
        internal static string DiseaseHistory {
            get {
                return ResourceManager.GetString("DiseaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Name.
        /// </summary>
        internal static string DiseaseName {
            get {
                return ResourceManager.GetString("DiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Attachment.
        /// </summary>
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Disease Stage.
        /// </summary>
        internal static string EditDiseaseStageDialogTitle {
            get {
                return ResourceManager.GetString("EditDiseaseStageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical History.
        /// </summary>
        internal static string EditMedicalHistory {
            get {
                return ResourceManager.GetString("EditMedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notification.
        /// </summary>
        internal static string EditNotification {
            get {
                return ResourceManager.GetString("EditNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date: {0}.
        /// </summary>
        internal static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email pattern..
        /// </summary>
        internal static string EmailInvalidPattern {
            get {
                return ResourceManager.GetString("EmailInvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        internal static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty!.
        /// </summary>
        internal static string Empty_Email {
            get {
                return ResourceManager.GetString("Empty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!.
        /// </summary>
        internal static string Empty_Password {
            get {
                return ResourceManager.GetString("Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the visit was not selected..
        /// </summary>
        internal static string EmptyDate {
            get {
                return ResourceManager.GetString("EmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor&apos;s data must not be blank..
        /// </summary>
        internal static string EmptyDoctorName {
            get {
                return ResourceManager.GetString("EmptyDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        internal static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name cannot be empty..
        /// </summary>
        internal static string EmptyFullname {
            get {
                return ResourceManager.GetString("EmptyFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be empty..
        /// </summary>
        internal static string EmptyNotificationDate {
            get {
                return ResourceManager.GetString("EmptyNotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be empty..
        /// </summary>
        internal static string EmptyNotificationTime {
            get {
                return ResourceManager.GetString("EmptyNotificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicted time of the visit must not be empty..
        /// </summary>
        internal static string EmptyPredictedTime {
            get {
                return ResourceManager.GetString("EmptyPredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street name cannot be blank..
        /// </summary>
        internal static string EmptyStreet {
            get {
                return ResourceManager.GetString("EmptyStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit description must not be empty..
        /// </summary>
        internal static string EmptyVisitDescription {
            get {
                return ResourceManager.GetString("EmptyVisitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be empty..
        /// </summary>
        internal static string EmptyVisitTime {
            get {
                return ResourceManager.GetString("EmptyVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit type must not be empty..
        /// </summary>
        internal static string EmptyVisitType {
            get {
                return ResourceManager.GetString("EmptyVisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the initial date..
        /// </summary>
        internal static string EndDateMustBeGreater {
            get {
                return ResourceManager.GetString("EndDateMustBeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening recommendations.
        /// </summary>
        internal static string EveningRecommendations {
            get {
                return ResourceManager.GetString("EveningRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length is {0}..
        /// </summary>
        internal static string ExceededMaxSizeOfField {
            get {
                return ResourceManager.GetString("ExceededMaxSizeOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required..
        /// </summary>
        internal static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size is {0} MB..
        /// </summary>
        internal static string FileMaximumSize {
            get {
                return ResourceManager.GetString("FileMaximumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        internal static string ForgetPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgetPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too long..
        /// </summary>
        internal static string FullNameTooLong {
            get {
                return ResourceManager.GetString("FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too short..
        /// </summary>
        internal static string FullNameTooShort {
            get {
                return ResourceManager.GetString("FullNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Edit Mode.
        /// </summary>
        internal static string GoToEditMode {
            get {
                return ResourceManager.GetString("GoToEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to main page.
        /// </summary>
        internal static string GoToMainPage {
            get {
                return ResourceManager.GetString("GoToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid postal code has been entered..
        /// </summary>
        internal static string IncorrectPostalCode {
            get {
                return ResourceManager.GetString("IncorrectPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment can only be submitted in .png, .jpg, or .pdf format..
        /// </summary>
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account uses an external authentication system ( Google or Facebook)..
        /// </summary>
        internal static string InvalidLoginProviderError {
            get {
                return ResourceManager.GetString("InvalidLoginProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must not be the same as the old one..
        /// </summary>
        internal static string InvalidNewPassword {
            get {
                return ResourceManager.GetString("InvalidNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        internal static string InvalidSignInCredentialsError {
            get {
                return ResourceManager.GetString("InvalidSignInCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the time periods must be selected (Morning, Evening, Afternoon, or Night)..
        /// </summary>
        internal static string InvalidTimeOfDay {
            get {
                return ResourceManager.GetString("InvalidTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, loading ....
        /// </summary>
        internal static string LoadingScreen {
            get {
                return ResourceManager.GetString("LoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you not have an account ?.
        /// </summary>
        internal static string LoginPageDontHaveAccountQuestion {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string LoginPageRegisterLink {
            get {
                return ResourceManager.GetString("LoginPageRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string LogOut_Dialog {
            get {
                return ResourceManager.GetString("LogOut_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        internal static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Assistant.
        /// </summary>
        internal static string MedicalAssist {
            get {
                return ResourceManager.GetString("MedicalAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added entry..
        /// </summary>
        internal static string MedicalHistoryAdded {
            get {
                return ResourceManager.GetString("MedicalHistoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the item from medical history..
        /// </summary>
        internal static string MedicalHistoryDeleted {
            get {
                return ResourceManager.GetString("MedicalHistoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Notes.
        /// </summary>
        internal static string MedicalNotes {
            get {
                return ResourceManager.GetString("MedicalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        internal static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recommendation has been removed..
        /// </summary>
        internal static string MedicationDeleted {
            get {
                return ResourceManager.GetString("MedicationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recommendation has been successfully updated..
        /// </summary>
        internal static string MedicationEdited {
            get {
                return ResourceManager.GetString("MedicationEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        internal static string MedicationName {
            get {
                return ResourceManager.GetString("MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of medication : {0}.
        /// </summary>
        internal static string MedicationNotificationCommunicate {
            get {
                return ResourceManager.GetString("MedicationNotificationCommunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Of Medication.
        /// </summary>
        internal static string MedicationNotificationType {
            get {
                return ResourceManager.GetString("MedicationNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine name is required.
        /// </summary>
        internal static string MedicineNameNotEmpty {
            get {
                return ResourceManager.GetString("MedicineNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning Recommendations.
        /// </summary>
        internal static string MorningRecommendations {
            get {
                return ResourceManager.GetString("MorningRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notification.
        /// </summary>
        internal static string NewNotifcation {
            get {
                return ResourceManager.GetString("NewNotifcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night recommendations.
        /// </summary>
        internal static string NightRecommendations {
            get {
                return ResourceManager.GetString("NightRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Medical Recommendations.
        /// </summary>
        internal static string NoRecommendationToday {
            get {
                return ResourceManager.GetString("NoRecommendationToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A note was added by default..
        /// </summary>
        internal static string NoteAdded {
            get {
                return ResourceManager.GetString("NoteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added notification..
        /// </summary>
        internal static string NotificationAdded {
            get {
                return ResourceManager.GetString("NotificationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Notification.
        /// </summary>
        internal static string NotificationDeleting {
            get {
                return ResourceManager.GetString("NotificationDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has been successfully edited..
        /// </summary>
        internal static string NotificationEdited {
            get {
                return ResourceManager.GetString("NotificationEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Language.
        /// </summary>
        internal static string NotificationLanguage {
            get {
                return ResourceManager.GetString("NotificationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Of Visit.
        /// </summary>
        internal static string NotificationOfVisit {
            get {
                return ResourceManager.GetString("NotificationOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments to choose from..
        /// </summary>
        internal static string NoVisitsToChoose {
            get {
                return ResourceManager.GetString("NoVisitsToChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visits .
        /// </summary>
        internal static string NoVisitsToday {
            get {
                return ResourceManager.GetString("NoVisitsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string PasswordChangeBtnLabel {
            get {
                return ResourceManager.GetString("PasswordChangeBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has just been sent with a link to change your password..
        /// </summary>
        internal static string PasswordChangedPageEmailSent {
            get {
                return ResourceManager.GetString("PasswordChangedPageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        internal static string PasswordChangeLabel {
            get {
                return ResourceManager.GetString("PasswordChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must matches..
        /// </summary>
        internal static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long. Maximum length is {0}..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short. Minimal length is {0}..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Visit Time.
        /// </summary>
        internal static string PredictedVisitTime {
            get {
                return ResourceManager.GetString("PredictedVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator of users&apos; personal data is the owner of the &apos;Medical Assistant&apos; application, who is responsible for their security and confidentiality..
        /// </summary>
        internal static string PrivacyAdminContent {
            get {
                return ResourceManager.GetString("PrivacyAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Data Administrator.
        /// </summary>
        internal static string PrivacyAdminTitle {
            get {
                return ResourceManager.GetString("PrivacyAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator reserves the right to change this Privacy Policy. Users will be notified of changes in advance..
        /// </summary>
        internal static string PrivacyChangesContent {
            get {
                return ResourceManager.GetString("PrivacyChangesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Changes to the Privacy Policy.
        /// </summary>
        internal static string PrivacyChangesTitle {
            get {
                return ResourceManager.GetString("PrivacyChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any questions or concerns regarding the processing of personal data, please contact us at: contact@medicalassistant.com..
        /// </summary>
        internal static string PrivacyContactContent {
            get {
                return ResourceManager.GetString("PrivacyContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Contact.
        /// </summary>
        internal static string PrivacyContactTitle {
            get {
                return ResourceManager.GetString("PrivacyContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information (e.g., email address)..
        /// </summary>
        internal static string PrivacyDataScopeContent1 {
            get {
                return ResourceManager.GetString("PrivacyDataScopeContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical and health data entered by the user (e.g., medical history, test results)..
        /// </summary>
        internal static string PrivacyDataScopeContent2 {
            get {
                return ResourceManager.GetString("PrivacyDataScopeContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Scope of Collected Data.
        /// </summary>
        internal static string PrivacyDataScopeTitle {
            get {
                return ResourceManager.GetString("PrivacyDataScopeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Privacy Policy sets out the principles for processing personal data of users using the &apos;Medical Assistant&apos; application..
        /// </summary>
        internal static string PrivacyGeneralContent {
            get {
                return ResourceManager.GetString("PrivacyGeneralContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. General Provisions.
        /// </summary>
        internal static string PrivacyGeneralTitle {
            get {
                return ResourceManager.GetString("PrivacyGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User consent provided during application registration..
        /// </summary>
        internal static string PrivacyLegalBasisContent1 {
            get {
                return ResourceManager.GetString("PrivacyLegalBasisContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal provisions requiring the processing of specific data (if applicable)..
        /// </summary>
        internal static string PrivacyLegalBasisContent2 {
            get {
                return ResourceManager.GetString("PrivacyLegalBasisContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Legal Basis for Data Processing.
        /// </summary>
        internal static string PrivacyLegalBasisTitle {
            get {
                return ResourceManager.GetString("PrivacyLegalBasisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyPostfix {
            get {
                return ResourceManager.GetString("PrivacyPolicyPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable the user to access the application&apos;s features..
        /// </summary>
        internal static string PrivacyPurposeContent1 {
            get {
                return ResourceManager.GetString("PrivacyPurposeContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage health data and medical history..
        /// </summary>
        internal static string PrivacyPurposeContent2 {
            get {
                return ResourceManager.GetString("PrivacyPurposeContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure application security and protect against misuse..
        /// </summary>
        internal static string PrivacyPurposeContent3 {
            get {
                return ResourceManager.GetString("PrivacyPurposeContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Purposes of Data Processing.
        /// </summary>
        internal static string PrivacyPurposeTitle {
            get {
                return ResourceManager.GetString("PrivacyPurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application uses technical and organizational measures to ensure the security of personal data processed and to protect it from unauthorized access, modification, disclosure, or destruction..
        /// </summary>
        internal static string PrivacySecurityContent {
            get {
                return ResourceManager.GetString("PrivacySecurityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Data Security.
        /// </summary>
        internal static string PrivacySecurityTitle {
            get {
                return ResourceManager.GetString("PrivacySecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data will not be shared with third parties without their consent, except as required by law..
        /// </summary>
        internal static string PrivacySharingContent {
            get {
                return ResourceManager.GetString("PrivacySharingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Sharing of Personal Data.
        /// </summary>
        internal static string PrivacySharingTitle {
            get {
                return ResourceManager.GetString("PrivacySharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to and correction of their data..
        /// </summary>
        internal static string PrivacyUserRightsContent1 {
            get {
                return ResourceManager.GetString("PrivacyUserRightsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of their data from the application..
        /// </summary>
        internal static string PrivacyUserRightsContent2 {
            get {
                return ResourceManager.GetString("PrivacyUserRightsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal of consent to data processing at any time..
        /// </summary>
        internal static string PrivacyUserRightsContent3 {
            get {
                return ResourceManager.GetString("PrivacyUserRightsContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. User Rights.
        /// </summary>
        internal static string PrivacyUserRightsTitle {
            get {
                return ResourceManager.GetString("PrivacyUserRightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate Account Again.
        /// </summary>
        internal static string ReactivateAccount {
            get {
                return ResourceManager.GetString("ReactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recommendation was successfully added..
        /// </summary>
        internal static string RecommendationAdded {
            get {
                return ResourceManager.GetString("RecommendationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email with the verification code has been sent..
        /// </summary>
        internal static string RegenerateCodeEmailSent {
            get {
                return ResourceManager.GetString("RegenerateCodeEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code Regeneration.
        /// </summary>
        internal static string RegenerateCodePageTitle {
            get {
                return ResourceManager.GetString("RegenerateCodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again verification link.
        /// </summary>
        internal static string RegenerateCodeSendAgain {
            get {
                return ResourceManager.GetString("RegenerateCodeSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was successfully set up..
        /// </summary>
        internal static string RegisterPageAccountCreated {
            get {
                return ResourceManager.GetString("RegisterPageAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation link was sent to your email address..
        /// </summary>
        internal static string RegisterPageEmailSent {
            get {
                return ResourceManager.GetString("RegisterPageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string RegisterPageLoginLink {
            get {
                return ResourceManager.GetString("RegisterPageLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account ?.
        /// </summary>
        internal static string RegisterPageQuestion {
            get {
                return ResourceManager.GetString("RegisterPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1. Using the Application may require registration and creation of a user account..
        /// </summary>
        internal static string Registration1 {
            get {
                return ResourceManager.GetString("Registration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2. The user agrees to provide truthful and current information during registration and update it as needed..
        /// </summary>
        internal static string Registration2 {
            get {
                return ResourceManager.GetString("Registration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3. The user account is personal, and access to it cannot be shared with third parties..
        /// </summary>
        internal static string Registration3 {
            get {
                return ResourceManager.GetString("Registration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Registration and User Account.
        /// </summary>
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulations.
        /// </summary>
        internal static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled date cannot be greater than visit date..
        /// </summary>
        internal static string ScheduledDateGreaterThanVisitDate {
            get {
                return ResourceManager.GetString("ScheduledDateGreaterThanVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Scheduled Date.
        /// </summary>
        internal static string ScheduledDateNotification {
            get {
                return ResourceManager.GetString("ScheduledDateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable text.
        /// </summary>
        internal static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected visit.
        /// </summary>
        internal static string SelectedVisit {
            get {
                return ResourceManager.GetString("SelectedVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a visit.
        /// </summary>
        internal static string SelectVisit {
            get {
                return ResourceManager.GetString("SelectVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved..
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stage was successfully added to the medical history..
        /// </summary>
        internal static string StageAdded {
            get {
                return ResourceManager.GetString("StageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Of Disease Stages.
        /// </summary>
        internal static string StageCount {
            get {
                return ResourceManager.GetString("StageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of disease stage.
        /// </summary>
        internal static string StageName {
            get {
                return ResourceManager.GetString("StageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully the entry was edited..
        /// </summary>
        internal static string SuccessfullyEdited {
            get {
                return ResourceManager.GetString("SuccessfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom Description.
        /// </summary>
        internal static string SymptomDescription {
            get {
                return ResourceManager.GetString("SymptomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags cannot be empty..
        /// </summary>
        internal static string TagsCannotBeEmpty {
            get {
                return ResourceManager.GetString("TagsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using the Medical Assistant Application!.
        /// </summary>
        internal static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Of Day.
        /// </summary>
        internal static string TimesOfDay {
            get {
                return ResourceManager.GetString("TimesOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        internal static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has not yet been activated..
        /// </summary>
        internal static string UnverifiedUserError {
            get {
                return ResourceManager.GetString("UnverifiedUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with given email was not found..
        /// </summary>
        internal static string UserNotFoundByGivenEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByGivenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code has expired..
        /// </summary>
        internal static string VerificationCodeExpiredLabel {
            get {
                return ResourceManager.GetString("VerificationCodeExpiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new code.
        /// </summary>
        internal static string VerificationCodeNewCode {
            get {
                return ResourceManager.GetString("VerificationCodeNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        internal static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit has already taken place..
        /// </summary>
        internal static string VisitAlreadyTakenPlace {
            get {
                return ResourceManager.GetString("VisitAlreadyTakenPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of visit: {0}.
        /// </summary>
        internal static string VisitDateCommunicate {
            get {
                return ResourceManager.GetString("VisitDateCommunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the visit..
        /// </summary>
        internal static string VisitDeletedText {
            get {
                return ResourceManager.GetString("VisitDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Details.
        /// </summary>
        internal static string VisitDetails {
            get {
                return ResourceManager.GetString("VisitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a visit for the hours given..
        /// </summary>
        internal static string VisitHoursConflict {
            get {
                return ResourceManager.GetString("VisitHoursConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such a medical visit no longer exists..
        /// </summary>
        internal static string VisitNotFound {
            get {
                return ResourceManager.GetString("VisitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications of visits.
        /// </summary>
        internal static string VisitNotifications {
            get {
                return ResourceManager.GetString("VisitNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical visit of the diagnosis.
        /// </summary>
        internal static string VisitOfDiagnosis {
            get {
                return ResourceManager.GetString("VisitOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Time Of Visit.
        /// </summary>
        internal static string VisitPredictedTime {
            get {
                return ResourceManager.GetString("VisitPredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Type.
        /// </summary>
        internal static string VisitType {
            get {
                return ResourceManager.GetString("VisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was read ?.
        /// </summary>
        internal static string WasRead {
            get {
                return ResourceManager.GetString("WasRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
