//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAssistant.UI.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicalAssistant.UI.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is already verified..
        /// </summary>
        internal static string AccountIsVerified {
            get {
                return ResourceManager.GetString("AccountIsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified..
        /// </summary>
        internal static string AccountVerifiedSuccess {
            get {
                return ResourceManager.GetString("AccountVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation link expired ?.
        /// </summary>
        internal static string ActivationLinkExpired {
            get {
                return ResourceManager.GetString("ActivationLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment.
        /// </summary>
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notification.
        /// </summary>
        internal static string AddNotification {
            get {
                return ResourceManager.GetString("AddNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Visit.
        /// </summary>
        internal static string AddVisitBtn {
            get {
                return ResourceManager.GetString("AddVisitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Visit.
        /// </summary>
        internal static string AddVisitTitle {
            get {
                return ResourceManager.GetString("AddVisitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the attachment ?.
        /// </summary>
        internal static string AttachmentDeletePrompt {
            get {
                return ResourceManager.GetString("AttachmentDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city name cannot be empty..
        /// </summary>
        internal static string CityCannotBeEmpty {
            get {
                return ResourceManager.GetString("CityCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmedPassword {
            get {
                return ResourceManager.GetString("ConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is already taken. .
        /// </summary>
        internal static string CreateAccountEmailInUsePrompt {
            get {
                return ResourceManager.GetString("CreateAccountEmailInUsePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currents.
        /// </summary>
        internal static string Currents {
            get {
                return ResourceManager.GetString("Currents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        internal static string CurrentWeek {
            get {
                return ResourceManager.GetString("CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sent.
        /// </summary>
        internal static string DateSent {
            get {
                return ResourceManager.GetString("DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachment.
        /// </summary>
        internal static string DeleteAttachment {
            get {
                return ResourceManager.GetString("DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this notification ?.
        /// </summary>
        internal static string DeletingNotificationQuestion {
            get {
                return ResourceManager.GetString("DeletingNotificationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing a Visit.
        /// </summary>
        internal static string DialogVisitRemoving {
            get {
                return ResourceManager.GetString("DialogVisitRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this visit ?.
        /// </summary>
        internal static string DialogVisitRemovingPrompt {
            get {
                return ResourceManager.GetString("DialogVisitRemovingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        internal static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Attachment.
        /// </summary>
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notification.
        /// </summary>
        internal static string EditNotification {
            get {
                return ResourceManager.GetString("EditNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email pattern..
        /// </summary>
        internal static string EmailInvalidPattern {
            get {
                return ResourceManager.GetString("EmailInvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        internal static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty!.
        /// </summary>
        internal static string Empty_Email {
            get {
                return ResourceManager.GetString("Empty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!.
        /// </summary>
        internal static string Empty_Password {
            get {
                return ResourceManager.GetString("Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the visit was not selected..
        /// </summary>
        internal static string EmptyDate {
            get {
                return ResourceManager.GetString("EmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor&apos;s data must not be blank..
        /// </summary>
        internal static string EmptyDoctorName {
            get {
                return ResourceManager.GetString("EmptyDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name cannot be empty..
        /// </summary>
        internal static string EmptyFullname {
            get {
                return ResourceManager.GetString("EmptyFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be empty..
        /// </summary>
        internal static string EmptyNotificationDate {
            get {
                return ResourceManager.GetString("EmptyNotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be empty..
        /// </summary>
        internal static string EmptyNotificationTime {
            get {
                return ResourceManager.GetString("EmptyNotificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicted time of the visit must not be empty..
        /// </summary>
        internal static string EmptyPredictedTime {
            get {
                return ResourceManager.GetString("EmptyPredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street name cannot be blank..
        /// </summary>
        internal static string EmptyStreet {
            get {
                return ResourceManager.GetString("EmptyStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit description must not be empty..
        /// </summary>
        internal static string EmptyVisitDescription {
            get {
                return ResourceManager.GetString("EmptyVisitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be empty..
        /// </summary>
        internal static string EmptyVisitTime {
            get {
                return ResourceManager.GetString("EmptyVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit type must not be empty..
        /// </summary>
        internal static string EmptyVisitType {
            get {
                return ResourceManager.GetString("EmptyVisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size is {0} MB..
        /// </summary>
        internal static string FileMaximumSize {
            get {
                return ResourceManager.GetString("FileMaximumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        internal static string ForgetPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgetPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too long..
        /// </summary>
        internal static string FullNameTooLong {
            get {
                return ResourceManager.GetString("FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is too short..
        /// </summary>
        internal static string FullNameTooShort {
            get {
                return ResourceManager.GetString("FullNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Edit Mode.
        /// </summary>
        internal static string GoToEditMode {
            get {
                return ResourceManager.GetString("GoToEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to main page.
        /// </summary>
        internal static string GoToMainPage {
            get {
                return ResourceManager.GetString("GoToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid postal code has been entered..
        /// </summary>
        internal static string IncorrectPostalCode {
            get {
                return ResourceManager.GetString("IncorrectPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment can only be submitted in .png, .jpg, or .pdf format..
        /// </summary>
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account uses an external authentication system ( Google or Facebook)..
        /// </summary>
        internal static string InvalidLoginProviderError {
            get {
                return ResourceManager.GetString("InvalidLoginProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must not be the same as the old one..
        /// </summary>
        internal static string InvalidNewPassword {
            get {
                return ResourceManager.GetString("InvalidNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        internal static string InvalidSignInCredentialsError {
            get {
                return ResourceManager.GetString("InvalidSignInCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, loading ....
        /// </summary>
        internal static string LoadingScreen {
            get {
                return ResourceManager.GetString("LoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you not have an account ?.
        /// </summary>
        internal static string LoginPageDontHaveAccountQuestion {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string LoginPageRegisterLink {
            get {
                return ResourceManager.GetString("LoginPageRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string LogOut_Dialog {
            get {
                return ResourceManager.GetString("LogOut_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        internal static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Assistant.
        /// </summary>
        internal static string MedicalAssist {
            get {
                return ResourceManager.GetString("MedicalAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added notification..
        /// </summary>
        internal static string NotificationAdded {
            get {
                return ResourceManager.GetString("NotificationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Notification.
        /// </summary>
        internal static string NotificationDeleting {
            get {
                return ResourceManager.GetString("NotificationDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has been successfully edited..
        /// </summary>
        internal static string NotificationEdited {
            get {
                return ResourceManager.GetString("NotificationEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Language.
        /// </summary>
        internal static string NotificationLanguage {
            get {
                return ResourceManager.GetString("NotificationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Of Visit.
        /// </summary>
        internal static string NotificationOfVisit {
            get {
                return ResourceManager.GetString("NotificationOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string PasswordChangeBtnLabel {
            get {
                return ResourceManager.GetString("PasswordChangeBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has just been sent with a link to change your password..
        /// </summary>
        internal static string PasswordChangedPageEmailSent {
            get {
                return ResourceManager.GetString("PasswordChangedPageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        internal static string PasswordChangeLabel {
            get {
                return ResourceManager.GetString("PasswordChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must matches..
        /// </summary>
        internal static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long. Maximum length is {0}..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short. Minimal length is {0}..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Visit Time.
        /// </summary>
        internal static string PredictedVisitTime {
            get {
                return ResourceManager.GetString("PredictedVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email with the verification code has been sent..
        /// </summary>
        internal static string RegenerateCodeEmailSent {
            get {
                return ResourceManager.GetString("RegenerateCodeEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code Regeneration.
        /// </summary>
        internal static string RegenerateCodePageTitle {
            get {
                return ResourceManager.GetString("RegenerateCodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again verification link.
        /// </summary>
        internal static string RegenerateCodeSendAgain {
            get {
                return ResourceManager.GetString("RegenerateCodeSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was successfully set up..
        /// </summary>
        internal static string RegisterPageAccountCreated {
            get {
                return ResourceManager.GetString("RegisterPageAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation link was sent to your email address..
        /// </summary>
        internal static string RegisterPageEmailSent {
            get {
                return ResourceManager.GetString("RegisterPageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string RegisterPageLoginLink {
            get {
                return ResourceManager.GetString("RegisterPageLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account ?.
        /// </summary>
        internal static string RegisterPageQuestion {
            get {
                return ResourceManager.GetString("RegisterPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled date cannot be greater than visit date..
        /// </summary>
        internal static string ScheduledDateGreaterThanVisitDate {
            get {
                return ResourceManager.GetString("ScheduledDateGreaterThanVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Scheduled Date.
        /// </summary>
        internal static string ScheduledDateNotification {
            get {
                return ResourceManager.GetString("ScheduledDateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        internal static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has not yet been activated..
        /// </summary>
        internal static string UnverifiedUserError {
            get {
                return ResourceManager.GetString("UnverifiedUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with given email was not found..
        /// </summary>
        internal static string UserNotFoundByGivenEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByGivenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code has expired..
        /// </summary>
        internal static string VerificationCodeExpiredLabel {
            get {
                return ResourceManager.GetString("VerificationCodeExpiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new code.
        /// </summary>
        internal static string VerificationCodeNewCode {
            get {
                return ResourceManager.GetString("VerificationCodeNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        internal static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit has already taken place..
        /// </summary>
        internal static string VisitAlreadyTakenPlace {
            get {
                return ResourceManager.GetString("VisitAlreadyTakenPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of visit: {0}.
        /// </summary>
        internal static string VisitDateCommunicate {
            get {
                return ResourceManager.GetString("VisitDateCommunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the visit..
        /// </summary>
        internal static string VisitDeletedText {
            get {
                return ResourceManager.GetString("VisitDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Details.
        /// </summary>
        internal static string VisitDetails {
            get {
                return ResourceManager.GetString("VisitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a visit for the hours given..
        /// </summary>
        internal static string VisitHoursConflict {
            get {
                return ResourceManager.GetString("VisitHoursConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such a medical visit no longer exists..
        /// </summary>
        internal static string VisitNotFound {
            get {
                return ResourceManager.GetString("VisitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications of visits.
        /// </summary>
        internal static string VisitNotifications {
            get {
                return ResourceManager.GetString("VisitNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Time Of Visit.
        /// </summary>
        internal static string VisitPredictedTime {
            get {
                return ResourceManager.GetString("VisitPredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Type.
        /// </summary>
        internal static string VisitType {
            get {
                return ResourceManager.GetString("VisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was read ?.
        /// </summary>
        internal static string WasRead {
            get {
                return ResourceManager.GetString("WasRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
