name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
   DOTNET_VERSION: "8.x"

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Setup
           uses: actions/setup-dotnet@v3
           with:
              dotnet-version: ${{ env.DOTNET_VERSION }}
         
         - name: Install Docker
           run: sudo apt-get update && sudo apt-get install -y docker.io
           
         - name: Restore
           run: dotnet restore ./MedicalAssistant.sln
         
         - name: Build
           run: dotnet build ./MedicalAssistant.sln --configuration Release --no-restore

         - name: Test
           run: dotnet test ./MedicalAssistant.sln --configuration Release --no-restore --no-build

